Organizations:
  - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/example.com/msp
  - &IBM
      Name: IBMMSP
      ID: IBMMSP
      MSPDir: crypto-config/peerOrganizations/ibm.example.com/msp
      AnchorPeers:
        - Host: peer0.ibm.example.com
          Port: 7051
  - &CBE
      Name: CBEMSP
      ID: CBEMSP
      MSPDir: crypto-config/peerOrganizations/cbe.example.com/msp
      AnchorPeers:
        - Host: peer0.cbe.example.com
          Port: 9051
Application: &ApplicationDefaults
  ? Organizations
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 15s
  BatchSize:
    MaxMessageCount: 30
    AbsoluteMaxBytes: 297 MB
    PreferredMaxBytes: 1536 KB
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  Organizations: null
Profiles:
  OrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      MyConsortium:
        Organizations:
          - *IBM
          - *CBE
  MyChannel:
    Consortium: MyConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *IBM
        - *CBE
